### ISSUE TITLE
can't find integration

### ISSUE THREAD

**Issue by Bascht74** [thebino/rki_covid#24]
Hi, 

first at all, thanks for this integration! Great work!

I installed it via HACS and configured the sensor in my sensor.yaml:

```
- platform: rki_covid
  districts:
   - name: 'LK Fulda'
   - name: 'LK Main-Kinzig-Kreis'
   - name: 'BL Hessen' 
```

After I restarted I want to add the new integration as stated:
`Add a new integration via Configuration > Integration and select your district to monitor.`

But I don't find anything...
Could you update the documentation and add the name of the integration you have to look for or - better - insert a picture of the relevant step...?

Maybe I am too stupid !?!?

In the logs I only find: 
```
2021-02-10 19:39:16 DEBUG (MainThread) [custom_components.rki_covid] Finished fetching rki_covid data in 1.549 seconds
[...]
2021-02-10 19:39:17 DEBUG (MainThread) [custom_components.rki_covid] Finished fetching rki_covid data in 0.187 seconds
```

But I don't have a clue how to do what you are saying...

Thanks for your help!
