### ISSUE TITLE
Different views in frontend after clicking on sensor card in frontend

### ISSUE THREAD

**Issue by UBS-P** [thebino/rki_covid#5]
Hello,
thanks for providing this integration.
I'm using the weekincidence as well as the deaths.
A click on the sensor card in lovelace frontend results in different actions:

- Click on weekincidence sensor card results in time bar view.
- Click on deaths sensor card results in trend view (like expected).
![incidence](https://user-images.githubusercontent.com/64033224/103129659-da385e80-4699-11eb-803d-f5d20e51dd7f.png)
![deaths](https://user-images.githubusercontent.com/64033224/103129665-defd1280-4699-11eb-83c8-bf2a610f0b80.png)

What can I do?
Thanks in advance
```
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.lk_tubingen_weekincidence
                graph: line
                detail: 2
                hours_to_show: 200
                name: Inzidenz TÜ
              - type: sensor
                entity: sensor.lk_tubingen_deaths
                graph: line
                detail: 2
                hours_to_show: 200
                name: Tote`
```
